"""
Configuration objects to facilitate using the Precomputed Connectome.

"""

import os
import json
from pathlib import Path

class Config:
    def __init__(self, pcc, stat):
        """Generate Config object.

        Parameters
        ----------
        pcc : str
            Path OR Name of configfile. If a filepath, assumed to be relative to current
            working directory or specified as absolute path. Otherwise, it is assumed a 
            config file with name `pcc` exists in $HOME/.config/pfctoolkit/.
        stat : tuple
            Determines if T, AvgR, or RFz maps will be generated by the PCC.

        Raises
        ------
        OSError
            Config is unable to be used because of missing resources.
        FileNotFoundError
            Requsted config file does not exist.
        """
        self.stat=stat
        self.checks = ["combo", "std", "norm", "chunk_idx"]
        
        if os.path.isfile(pcc):
            configfile = pcc
        else:
            home = os.path.expanduser('~')
            config_dir = os.path.join(home, ".config/pfctoolkit")
            Path(config_dir).mkdir(parents=True, exist_ok=True)
            configfile = os.path.join(config_dir, f"{pcc}.json")
        try:
            with open(str(configfile)) as js:
                self.config = json.load(js)
            if self.check():
                print(f"Config {self.config['name']} loaded")
            else:
                print(self.check())
                raise OSError(f"Config {self.config['name']} unavailable")
        except FileNotFoundError:
            raise FileNotFoundError(f"PCC config file {configfile} does not exist!")

    def check(self):
        """Check that all resources specified in config file are accessible and exist.
        
        Returns
        -------
        bool
            If True, then all resources specified in config file are accessible and
            exist.
        """
        for stat_choice in self.stat:
            self.checks.append(stat_choice)
        if (all(list(map(os.path.exists, [self.config[key] for key in self.checks])))):
            return True
        elif self.config.get("use_s3", False):
            for key in self.checks:
                if not os.path.exists(self.config[key]):
                    print(f"WARNING: {key} cannot be found locally-- we will assume it is on S3.")
            return True
        else:
            return False

    def get(self, key, default=None):
        """Get value in config specified by key.

        Parameters
        ----------
        key : str
            Key of value to retrieve from config.
        default : str, optional

        Returns
        -------
        str
            Value of Key in config.
        """
        if key in self.config:
            return self.config[key]
        else:
            return default


    def get_config(self):
        """Get config as dict.

        Returns
        -------
        dict
            Configuration as dict.
        """
        return self.config
