"""
Configuration objects to facilitate using the Precomputed Connectome.

"""

import os
import json


class Config:
    def __init__(self, pcc, stat, use_default_dir=True):
        """Generate Config object.

        Parameters
        ----------
        pcc : str
            Name of configfile. Must exist in $HOME/.config/pfctoolkit/.
        stat : tuple
            Determines if T, AvgR, or RFz maps will be generated by the PCC.
        use_default_dir : bool, optional
            If True, then the config file is assumed to be in $HOME/pfctoolkit_config/.
            If False, then the config file is assumed to be in the current working directory or specified as an absolute path.

        Raises
        ------
        OSError
            Config is unable to be used because of missing resources.
        FileNotFoundError
            Requsted config file does not exist.
        """
        self.stat=stat
        self.checks = ["combo", "std", "norm", "chunk_idx"]
        
        home = os.path.expanduser('~')
        if not use_default_dir:
            configfile = pcc
        else:
            configfile = os.path.join(home, f".config/pfctoolkit/{pcc}.json")
        try:
            with open(str(configfile)) as js:
                self.config = json.load(js)
            if self.check():
                print(f"Config {self.config['name']} loaded")
            else:
                print(self.check())
                raise OSError(f"Config {self.config['name']} unavailable")
        except FileNotFoundError:
            raise FileNotFoundError(f"PCC config file {configfile} does not exist!")

    def check(self):
        """Check that all resources specified in config file are accessible and exist.
        
        Returns
        -------
        bool
            If True, then all resources specified in config file are accessible and
            exist.
        """
        for stat_choice in self.stat:
            self.checks.append(stat_choice)
        if (all(list(map(os.path.exists, [self.config[key] for key in self.checks])))):
            return True
        elif self.config.get("use_s3", False):
            for key in self.checks:
                if not os.path.exists(self.config[key]):
                    print(f"WARNING: {key} cannot be found locally-- we will assume it is on S3.")
            return True
        else:
            return False

    def get(self, key, default=None):
        """Get value in config specified by key.

        Parameters
        ----------
        key : str
            Key of value to retrieve from config.
        default : str, optional

        Returns
        -------
        str
            Value of Key in config.
        """
        if key in self.config:
            return self.config[key]
        else:
            return default


    def get_config(self):
        """Get config as dict.

        Returns
        -------
        dict
            Configuration as dict.
        """
        return self.config
